name: Code coverage
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - name: Install lcov dependency
        run: |
          sudo apt --assume-yes update
          sudo apt --assume-yes install lcov
      - name: CMake configure
        run: cmake -DENABLE_INTEL_MYRIAD_COMMON=OFF -DCMAKE_BUILD_TYPE=Release -DENABLE_FASTER_BUILD=ON -DENABLE_OV_ONNX_FRONTEND=ON -DENABLE_TESTS=ON -DENABLE_COVERAGE=ON -DENABLE_INTEL_GPU=OFF -B build

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Build OpenVINO
        run:  cmake --build build --target all --parallel ${{ steps.cpu-cores.outputs.count }}

      - name: ls all
        run:  ls -laR .

      - name: Run tests
        run: ctest -V

      - name: Build coverage
        run:  cmake --build build --target ov_coverage

      - name: Generate raport
        run: |
          lcov --capture --directory . --output-file coverage.info
          genhtml coverage.info --output-directory coverage-report 

      - name: Collect coverage
        uses: codecov/codecov-action@v3
        with:
          verbose: true